line-length = 100

[lint]
select = ["ALL"]
ignore = ["T201", # Do not check for prints()
  "D203", # Remove blank line after class
  "COM812", # Don't check for missing trailing commas
  "D212"] # Docstring summary lines must not be positioned on the first physical line.
